export type Hospital = {
  id: number;
  name: string;
  district: string;
  address: string;
  lat: number;
  lng: number;
  phone: string;
  has_obstetrics: boolean;
  has_pediatrics: boolean;
  has_emergency: boolean;
  type: "hospital";
};

export const HOSPITALS: Hospital[] = [
  {
    id: 1,
    name: "부산대학교병원",
    district: "서구",
    address: "부산광역시 서구 구덕로 179",
    lat: 35.1068,
    lng: 129.0228,
    phone: "051-240-7000",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 2,
    name: "인제대학교 해운대백병원",
    district: "해운대구",
    address: "부산광역시 해운대구 해운대로 875",
    lat: 35.1631,
    lng: 129.1680,
    phone: "051-797-0100",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 3,
    name: "인제대학교 부산백병원",
    district: "부산진구",
    address: "부산광역시 부산진구 복지로 75",
    lat: 35.1579,
    lng: 129.0538,
    phone: "051-890-6114",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 4,
    name: "동아대학교병원",
    district: "서구",
    address: "부산광역시 서구 대신공원로 26",
    lat: 35.1047,
    lng: 129.0138,
    phone: "051-240-2000",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 5,
    name: "좋은문화병원",
    district: "부산진구",
    address: "부산광역시 부산진구 새싹로 57",
    lat: 35.1490,
    lng: 129.0620,
    phone: "051-630-0500",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: false,
    type: "hospital",
  },
  {
    id: 6,
    name: "좋은삼선병원",
    district: "사상구",
    address: "부산광역시 사상구 학감대로 199",
    lat: 35.1503,
    lng: 128.9918,
    phone: "051-320-7000",
    has_obstetrics: false,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 7,
    name: "좋은강안병원",
    district: "수영구",
    address: "부산광역시 수영구 수영로 706",
    lat: 35.1451,
    lng: 129.1124,
    phone: "051-610-2000",
    has_obstetrics: false,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 8,
    name: "메리놀병원",
    district: "중구",
    address: "부산광역시 중구 중구로 121",
    lat: 35.1040,
    lng: 129.0326,
    phone: "051-461-2000",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 9,
    name: "일신기독병원",
    district: "동구",
    address: "부산광역시 동구 일신로 52",
    lat: 35.1210,
    lng: 129.0545,
    phone: "051-630-0300",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: false,
    type: "hospital",
  },
  {
    id: 10,
    name: "부산성모병원",
    district: "남구",
    address: "부산광역시 남구 용호로 232번길 25",
    lat: 35.1207,
    lng: 129.0995,
    phone: "051-933-7114",
    has_obstetrics: false,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 11,
    name: "고신대학교복음병원",
    district: "서구",
    address: "부산광역시 서구 감천로 262",
    lat: 35.0933,
    lng: 129.0108,
    phone: "051-990-6114",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 12,
    name: "양산부산대학교병원",
    district: "양산",
    address: "경상남도 양산시 물금읍 금오로 20",
    lat: 35.3394,
    lng: 129.0011,
    phone: "055-360-2001",
    has_obstetrics: true,
    has_pediatrics: true,
    has_emergency: true,
    type: "hospital",
  },
  {
    id: 13,
    name: "동남권원자력의학원",
    district: "기장군",
    address: "부산광역시 기장군 장안읍 좌동길 40",
    lat: 35.3613,
    lng: 129.2464,
    phone: "051-720-5114",
    has_obstetrics: false,
    has_pediatrics: false,
    has_emergency: true,
    type: "hospital",
  },
];
